language: python

python:
  - "3.5.2"

install:
  - pip install -r requirements.txt

  - pip install coveralls

  - pip install codeclimate-test-reporter

  - pip install pytest pytest-cov

  - pip install codecov


env:
  - FLASK_VERSION=1.0.2
  - CODECOV_TOKEN="5ab3ec76-122a-46b6-bb41-0583fb9216e1

script:
  - pytest --cov=/app
  - coveralls


after_success:
  - coveralls
  - codeclimate-test-reporter
  - codecov