language: python

python:
  - "3.5.2"

install:
  - pip install -r requirements.txt

  - pip install coveralls

  - pip install codeclimate-test-reporter

  - pip install pytest pytest-cov


env:
  - FLASK_VERSION=1.0.2

script:
  - pytest --cov=./app/api/tests/v1/
  - coveralls


after_success:
  - coveralls
  - codeclimate-test-reporter